import type { NextPage } from "next";
import Head from "next/head";
import { Feeds, Header, Sidebar, Widgets } from "../components";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Bongo Bee</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className="flex justify-between ">
				<Sidebar />
				<Feeds />
				<Widgets />
			</main>
		</div>
	);
};

export default Home;
